### ISSUE TITLE
make

### ISSUE THREAD

**Issue by sec13b** [safedv/RustiveDump#2]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\test\Desktop\RustiveDump-main>cargo make
error: no such command: `make`

        Did you mean `add`?

        View all installed commands with `cargo --list`
        Find a package to install `make` with `cargo search cargo-make`

C:\Users\test\Desktop\RustiveDump-main>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo search make ??

**Comment by GeneralBison** [comment]
This isn't an issue with RustiveDump so shouldn't really be here, there is no 'make' command with cargo, if you're trying to build it's `cargo build`.

**Comment by safedv** [comment]
Install `cargo-make` to use the `cargo make` command:

`cargo install cargo-make`

Once installed, `cargo make` should work as expected.
